# Feature Engineering
The process of creating, transforming, or selecting input variables (features) from raw data to improve the performance of machine learning models. It often involves techniques like scaling, encoding categorical data, creating new features from existing ones, or reducing dimensionality. Essentially, it’s about turning raw data into meaningful inputs that help models learn patterns more effectively.

Create meaningful features:
- One-hot encoding
- Extract date features (weekday, month, hour…)
- Domain logic features
- Combine or derive features (ratios, interactions)
- Transform skew (log transform)
- Text preprocessing (tokenisation, embeddings)

Here we will be using pandas to handle storing and processing the data

In [75]:
import pandas as pd

df = pd.read_csv("data/nba_games.csv",index_col=0)

In [76]:
df["won_opp"] = ~df["won"]

In [77]:
df.tail()

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,won_opp
25685,240.0,40.0,94.0,0.426,14.0,32.0,0.438,26.0,32.0,19.0,...,32.2,230.0,136.0,IND,109,0,2025,2025-06-16,True,False
25686,240.0,31.0,74.0,0.419,8.0,30.0,0.267,21.0,26.0,4.0,...,28.4,177.0,102.0,IND,108,1,2025,2025-06-19,False,True
25687,240.0,38.0,92.0,0.413,15.0,42.0,0.357,17.0,25.0,11.0,...,44.1,186.0,114.0,OKC,91,0,2025,2025-06-19,True,False
25688,240.0,29.0,70.0,0.414,11.0,28.0,0.393,22.0,29.0,12.0,...,82.8,162.0,114.0,OKC,103,1,2025,2025-06-22,False,True
25689,240.0,35.0,87.0,0.402,11.0,40.0,0.275,22.0,31.0,13.0,...,42.5,134.0,123.0,IND,91,0,2025,2025-06-22,True,False

In [78]:
with pd.option_context(
    'display.max_rows', None,
    'display.max_columns', None,
    'display.max_colwidth', None,
    'display.width', None
):
    print(df.tail(2))

          mp    fg   fga    fg%    3p   3pa    3p%    ft   fta   orb   drb  \
25688  240.0  29.0  70.0  0.414  11.0  28.0  0.393  22.0  29.0  12.0  33.0
25689  240.0  35.0  87.0  0.402  11.0  40.0  0.275  22.0  31.0  13.0  27.0

        trb   ast   stl  blk   tov    pf    pts    ts%   efg%  3par    ftr  \
25688  45.0  17.0   6.0  4.0  23.0  24.0   91.0  0.550  0.493  0.40  0.414
25689  40.0  20.0  14.0  8.0   8.0  23.0  103.0  0.512  0.466  0.46  0.356

       orb%  drb%  trb%  ast%  stl%  blk%  tov%   usg%   ortg   drtg  fg_max  \
25688  30.8  71.7  52.9  58.6   6.6   8.5  21.7  100.0   99.6  112.7     8.0
25689  28.3  69.2  47.1  57.1  15.3  19.0   7.4  100.0  112.7   99.6     8.0

       fga_max  fg%_max  3p_max  3pa_max  3p%_max  ft_max  fta_max  orb_max  \
25688     14.0    0.615     3.0      5.0    0.750    10.0     10.0      7.0
25689     27.0    0.750     2.0     12.0    0.667    11.0     12.0      3.0

       drb_max  trb_max  ast_max  stl_max  blk_max  tov_max  pf_max  pts_max  \
25688      6.0     13.0      6.0      2.0      2.0      7.0     6.0     24.0
25689      6.0      9.0     12.0      3.0      5.0      2.0     5.0     29.0

       gmsc_max  ts%_max  efg%_max  3par_max  ftr_max  orb%_max  drb%_max  \
25688      23.2    1.136     0.900       1.0      1.0      25.8      22.3
25689      22.2    0.833     0.833       1.0      1.0      22.6      40.5

       trb%_max  ast%_max  stl%_max  blk%_max  tov%_max  usg%_max  ortg_max  \
25688      22.0      33.4       3.4       6.7      53.2      42.5     134.0
25689      27.9      56.3       6.0      18.3     100.0      82.8     162.0

       drtg_max team  total  home  mp_opp  fg_opp  fga_opp  fg%_opp  3p_opp  \
25688     123.0  IND     91     0   240.0    35.0     87.0    0.402    11.0
25689     114.0  OKC    103     1   240.0    29.0     70.0    0.414    11.0

       3pa_opp  3p%_opp  ft_opp  fta_opp  orb_opp  drb_opp  trb_opp  ast_opp  \
25688     40.0    0.275    22.0     31.0     13.0     27.0     40.0     20.0
25689     28.0    0.393    22.0     29.0     12.0     33.0     45.0     17.0

       stl_opp  blk_opp  tov_opp  pf_opp  pts_opp  ts%_opp  efg%_opp  \
25688     14.0      8.0      8.0    23.0    103.0    0.512     0.466
25689      6.0      4.0     23.0    24.0     91.0    0.550     0.493

       3par_opp  ftr_opp  orb%_opp  drb%_opp  trb%_opp  ast%_opp  stl%_opp  \
25688      0.46    0.356      28.3      69.2      47.1      57.1      15.3
25689      0.40    0.414      30.8      71.7      52.9      58.6       6.6

       blk%_opp  tov%_opp  usg%_opp  ortg_opp  drtg_opp  fg_max_opp  \
25688      19.0       7.4     100.0     112.7      99.6         8.0
25689       8.5      21.7     100.0      99.6     112.7         8.0

       fga_max_opp  fg%_max_opp  3p_max_opp  3pa_max_opp  3p%_max_opp  \
25688         27.0        0.750         2.0         12.0        0.667
25689         14.0        0.615         3.0          5.0        0.750

       ft_max_opp  fta_max_opp  orb_max_opp  drb_max_opp  trb_max_opp  \
25688        11.0         12.0          3.0          6.0          9.0
25689        10.0         10.0          7.0          6.0         13.0

       ast_max_opp  stl_max_opp  blk_max_opp  tov_max_opp  pf_max_opp  \
25688         12.0          3.0          5.0          2.0         5.0
25689          6.0          2.0          2.0          7.0         6.0

       pts_max_opp  gmsc_max_opp  ts%_max_opp  efg%_max_opp  3par_max_opp  \
25688         29.0          22.2        0.833         0.833           1.0
25689         24.0          23.2        1.136         0.900           1.0

       ftr_max_opp  orb%_max_opp  drb%_max_opp  trb%_max_opp  ast%_max_opp  \
25688          1.0          22.6          40.5          27.9          56.3
25689          1.0          25.8          22.3          22.0          33.4

       stl%_max_opp  blk%_max_opp  tov%_max_opp  usg%_max_opp  ortg_max_opp  \
25688           6.0          18.3         100.0          82.8         162.0
25689           3.4           6.7          53.2          42.5         134.0

       drtg_max_opp team_opp  total_opp  home_opp  season        date    won  \
25688         114.0      OKC        103         1    2025  2025-06-22  False
25689         123.0      IND         91         0    2025  2025-06-22   True

       won_opp
25688     True
25689    False

In [79]:
df_test = df.sort_values(["team_opp", "date"])
df_test[["team_opp","date"]]

      team_opp        date
12806      ATL  2020-12-23
12832      ATL  2020-12-26
12868      ATL  2020-12-28
12897      ATL  2020-12-30
12933      ATL  2021-01-01
...        ...         ...
25392      WAS  2025-04-06
25413      WAS  2025-04-08
25425      WAS  2025-04-09
25473      WAS  2025-04-11
25494      WAS  2025-04-13

[12908 rows x 2 columns]

### Adding days rested since last game

In [80]:
def set_days_rested(df,team,prev_date,days_rested):
    # Sort within each team by date
    df = df.sort_values([team, "date"])

    # Compute previous game date for each team
    df[prev_date] = df.groupby(team)["date"].shift(1)
    
    #Set the dates as datetime
    df["date"] = pd.to_datetime(df["date"])
    df[prev_date] = pd.to_datetime(df[prev_date])

    # Difference in days
    df[days_rested] = (df["date"] - df[prev_date]).dt.days

    # First game of the season has no previous game → fill with something reasonable
    df[days_rested] = df[days_rested].fillna(0)

    return df

def set_both_teams_days_rested(df):
    df = set_days_rested(df,"team","prev_date","days_rested")
    df = set_days_rested(df,"team_opp","prev_date_opp","days_rested_opp")
    return df

df = set_both_teams_days_rested(df)

In [81]:
df = df.dropna()
df = df.sort_values("date")

In [82]:
df = df[df["days_rested"] <= 4]
df = df[df["days_rested_opp"] <= 4]

In [83]:
df[["team","team_opp","home","season","days_rested","days_rested_opp","won"]].head(20)

      team team_opp  home  season  days_rested  days_rested_opp    won
12815  DAL      LAL     0    2021          2.0              3.0  False
12810  MIL      GSW     1    2021          2.0              3.0   True
12819  BRK      BOS     0    2021          3.0              2.0   True
12812  MIA      NOP     1    2021          2.0              2.0   True
12816  DEN      LAC     1    2021          2.0              3.0  False
12818  BOS      BRK     1    2021          2.0              3.0  False
12817  LAC      DEN     0    2021          3.0              2.0   True
12811  GSW      MIL     0    2021          3.0              2.0  False
12813  NOP      MIA     0    2021          2.0              2.0  False
12814  LAL      DAL     1    2021          3.0              2.0   True
12825  TOR      SAS     0    2021          3.0              3.0  False
12831  PHI      NYK     0    2021          3.0              3.0   True
12838  IND      CHI     0    2021          3.0              3.0   True
12832  MEM      ATL     1    2021          3.0              3.0  False
12839  NYK      PHI     1    2021          3.0              3.0  False
12824  SAS      TOR     1    2021          3.0              3.0   True
12826  SAC      PHO     1    2021          3.0              3.0   True
12827  PHO      SAC     0    2021          3.0              3.0  False
12820  WAS      ORL     1    2021          3.0              3.0  False
12822  UTA      MIN     1    2021          3.0              3.0  False

In [84]:
df.head()

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,total_opp,home_opp,season,date,won,won_opp,prev_date,days_rested,prev_date_opp,days_rested_opp
12815,240.0,41.0,83.0,0.494,13.0,32.0,0.406,20.0,26.0,3.0,...,138,1,2021,2020-12-25,False,True,2020-12-23,2.0,2020-12-22,3.0
12810,240.0,50.0,90.0,0.556,20.0,36.0,0.556,18.0,26.0,11.0,...,99,0,2021,2020-12-25,True,False,2020-12-23,2.0,2020-12-22,3.0
12819,240.0,41.0,76.0,0.539,15.0,29.0,0.517,26.0,31.0,9.0,...,95,1,2021,2020-12-25,True,False,2020-12-22,3.0,2020-12-23,2.0
12812,240.0,38.0,75.0,0.507,16.0,37.0,0.432,19.0,23.0,4.0,...,98,0,2021,2020-12-25,True,False,2020-12-23,2.0,2020-12-23,2.0
12816,240.0,37.0,81.0,0.457,11.0,36.0,0.306,23.0,31.0,10.0,...,121,0,2021,2020-12-25,False,True,2020-12-23,2.0,2020-12-22,3.0

In [85]:
for col in df.columns:
    print(col)

mp
fg
fga
fg%
3p
3pa
3p%
ft
fta
orb
drb
trb
ast
stl
blk
tov
pf
pts
ts%
efg%
3par
ftr
orb%
drb%
trb%
ast%
stl%
blk%
tov%
usg%
ortg
drtg
fg_max
fga_max
fg%_max
3p_max
3pa_max
3p%_max
ft_max
fta_max
orb_max
drb_max
trb_max
ast_max
stl_max
blk_max
tov_max
pf_max
pts_max
gmsc_max
ts%_max
efg%_max
3par_max
ftr_max
orb%_max
drb%_max
trb%_max
ast%_max
stl%_max
blk%_max
tov%_max
usg%_max
ortg_max
drtg_max
team
total
home
mp_opp
fg_opp
fga_opp
fg%_opp
3p_opp
3pa_opp
3p%_opp
ft_opp
fta_opp
orb_opp
drb_opp
trb_opp
ast_opp
stl_opp
blk_opp
tov_opp
pf_opp
pts_opp
ts%_opp
efg%_opp
3par_opp
ftr_opp
orb%_opp
drb%_opp
trb%_opp
ast%_opp
stl%_opp
blk%_opp
tov%_opp
usg%_opp
ortg_opp
drtg_opp
fg_max_opp
fga_max_opp
fg%_max_opp
3p_max_opp
3pa_max_opp
3p%_max_opp
ft_max_opp
fta_max_opp
orb_max_opp
drb_max_opp
trb_max_opp
ast_max_opp
stl_max_opp
blk_max_opp
tov_max_opp
pf_max_opp
pts_max_opp
gmsc_max_opp
ts%_max_opp
efg%_max_opp
3par_max_opp
ftr_max_opp
orb%_max_opp
drb%_max_opp
trb%_max_opp
ast%_max_opp
stl%_max_opp
blk%_max_opp
tov%_max_opp
usg%_max_opp
ortg_max_opp
drtg_max_opp
team_opp
total_opp
home_opp
season
date
won
won_opp
prev_date
days_rested
prev_date_opp
days_rested_opp

## Rolling averages
First useful feature to add to our dataframe is the rolling averages which our model can use to see how each team is performing over their last 10 games

In [86]:
removed_columns = ["season", "date", "team", "team_opp"]
selected_columns = list(df.columns[~df.columns.isin(removed_columns)])
opp_columns = [c for c in selected_columns if "_opp" in c]
team_columns = list(df.columns[~df.columns.isin(removed_columns + opp_columns)])

In [87]:
def find_team_averages(group,n):
    # Compute rolling mean with an n-game window, shifted so current row isn’t included
    return group.shift().rolling(n, min_periods=1).mean()

def get_rolling_df(df,keys,cols_to_roll,n):
    df = df.sort_values([keys[0],"date"])
    df_rolling = find_team_averages(df.groupby(keys, group_keys=False)[cols_to_roll],n)
    rolling_cols = [f"{col}_{n}" for col in df_rolling.columns]
    df_rolling.columns = rolling_cols
    return df_rolling

df_rolling_10 = get_rolling_df(df,["team","season"],team_columns,10)
df_rolling_5 = get_rolling_df(df,["team","season"],team_columns,5)

df_rolling_10_opp = get_rolling_df(df,["team_opp","season"],opp_columns,10)
df_rolling_5_opp = get_rolling_df(df,["team_opp","season"],opp_columns,5)

df = pd.concat([df, df_rolling_5, df_rolling_10, df_rolling_10_opp, df_rolling_5_opp], axis=1)

In [88]:
with pd.option_context(
    'display.max_rows', None,
    'display.max_columns', None,
    'display.max_colwidth', None,
    'display.width', None
):
    print(df.tail(2))

          mp    fg   fga    fg%    3p   3pa    3p%    ft   fta   orb   drb  \
25688  240.0  29.0  70.0  0.414  11.0  28.0  0.393  22.0  29.0  12.0  33.0
25689  240.0  35.0  87.0  0.402  11.0  40.0  0.275  22.0  31.0  13.0  27.0

        trb   ast   stl  blk   tov    pf    pts    ts%   efg%  3par    ftr  \
25688  45.0  17.0   6.0  4.0  23.0  24.0   91.0  0.550  0.493  0.40  0.414
25689  40.0  20.0  14.0  8.0   8.0  23.0  103.0  0.512  0.466  0.46  0.356

       orb%  drb%  trb%  ast%  stl%  blk%  tov%   usg%   ortg   drtg  fg_max  \
25688  30.8  71.7  52.9  58.6   6.6   8.5  21.7  100.0   99.6  112.7     8.0
25689  28.3  69.2  47.1  57.1  15.3  19.0   7.4  100.0  112.7   99.6     8.0

       fga_max  fg%_max  3p_max  3pa_max  3p%_max  ft_max  fta_max  orb_max  \
25688     14.0    0.615     3.0      5.0    0.750    10.0     10.0      7.0
25689     27.0    0.750     2.0     12.0    0.667    11.0     12.0      3.0

       drb_max  trb_max  ast_max  stl_max  blk_max  tov_max  pf_max  pts_max  \
25688      6.0     13.0      6.0      2.0      2.0      7.0     6.0     24.0
25689      6.0      9.0     12.0      3.0      5.0      2.0     5.0     29.0

       gmsc_max  ts%_max  efg%_max  3par_max  ftr_max  orb%_max  drb%_max  \
25688      23.2    1.136     0.900       1.0      1.0      25.8      22.3
25689      22.2    0.833     0.833       1.0      1.0      22.6      40.5

       trb%_max  ast%_max  stl%_max  blk%_max  tov%_max  usg%_max  ortg_max  \
25688      22.0      33.4       3.4       6.7      53.2      42.5     134.0
25689      27.9      56.3       6.0      18.3     100.0      82.8     162.0

       drtg_max team  total  home  mp_opp  fg_opp  fga_opp  fg%_opp  3p_opp  \
25688     123.0  IND     91     0   240.0    35.0     87.0    0.402    11.0
25689     114.0  OKC    103     1   240.0    29.0     70.0    0.414    11.0

       3pa_opp  3p%_opp  ft_opp  fta_opp  orb_opp  drb_opp  trb_opp  ast_opp  \
25688     40.0    0.275    22.0     31.0     13.0     27.0     40.0     20.0
25689     28.0    0.393    22.0     29.0     12.0     33.0     45.0     17.0

       stl_opp  blk_opp  tov_opp  pf_opp  pts_opp  ts%_opp  efg%_opp  \
25688     14.0      8.0      8.0    23.0    103.0    0.512     0.466
25689      6.0      4.0     23.0    24.0     91.0    0.550     0.493

       3par_opp  ftr_opp  orb%_opp  drb%_opp  trb%_opp  ast%_opp  stl%_opp  \
25688      0.46    0.356      28.3      69.2      47.1      57.1      15.3
25689      0.40    0.414      30.8      71.7      52.9      58.6       6.6

       blk%_opp  tov%_opp  usg%_opp  ortg_opp  drtg_opp  fg_max_opp  \
25688      19.0       7.4     100.0     112.7      99.6         8.0
25689       8.5      21.7     100.0      99.6     112.7         8.0

       fga_max_opp  fg%_max_opp  3p_max_opp  3pa_max_opp  3p%_max_opp  \
25688         27.0        0.750         2.0         12.0        0.667
25689         14.0        0.615         3.0          5.0        0.750

       ft_max_opp  fta_max_opp  orb_max_opp  drb_max_opp  trb_max_opp  \
25688        11.0         12.0          3.0          6.0          9.0
25689        10.0         10.0          7.0          6.0         13.0

       ast_max_opp  stl_max_opp  blk_max_opp  tov_max_opp  pf_max_opp  \
25688         12.0          3.0          5.0          2.0         5.0
25689          6.0          2.0          2.0          7.0         6.0

       pts_max_opp  gmsc_max_opp  ts%_max_opp  efg%_max_opp  3par_max_opp  \
25688         29.0          22.2        0.833         0.833           1.0
25689         24.0          23.2        1.136         0.900           1.0

       ftr_max_opp  orb%_max_opp  drb%_max_opp  trb%_max_opp  ast%_max_opp  \
25688          1.0          22.6          40.5          27.9          56.3
25689          1.0          25.8          22.3          22.0          33.4

       stl%_max_opp  blk%_max_opp  tov%_max_opp  usg%_max_opp  ortg_max_opp  \
25688           6.0          18.3         100.0          82.8         162.0
25689           3.4           6.7          53.2          42.5         134.0

       drtg_max_opp team_opp  total_opp  home_opp  season       date    won  \
25688         114.0      OKC        103         1    2025 2025-06-22  False
25689         123.0      IND         91         0    2025 2025-06-22   True

       won_opp  prev_date  days_rested prev_date_opp  days_rested_opp   mp_5  \
25688     True 2025-06-19          3.0    2025-06-19              3.0  240.0
25689    False 2025-06-19          3.0    2025-06-19              3.0  240.0

       fg_5  fga_5   fg%_5  3p_5  3pa_5   3p%_5  ft_5  fta_5  orb_5  drb_5  \
25688  38.0   84.2  0.4516  12.0   35.0  0.3426  20.8   27.2   10.0   30.0
25689  37.0   81.4  0.4550   9.8   27.2  0.3474  26.6   31.8   11.0   31.8

       trb_5  ast_5  stl_5  blk_5  tov_5  pf_5  pts_5   ts%_5  efg%_5  3par_5  \
25688   40.0   23.6   11.6    5.8   15.8  23.6  108.8  0.5664  0.5230  0.4158
25689   42.8   18.0    9.4    5.4   16.2  22.0  110.4  0.5782  0.5144  0.3334

        ftr_5  orb%_5  drb%_5  trb%_5  ast%_5  stl%_5  blk%_5  tov%_5  usg%_5  \
25688  0.3254   23.52   73.78    48.0   62.40   11.76   11.00   14.06   100.0
25689  0.3920   26.22   76.48    52.0   48.12    9.60   10.86   14.64   100.0

       ortg_5  drtg_5  fg_max_5  fga_max_5  fg%_max_5  3p_max_5  3pa_max_5  \
25688  110.54  112.34       7.6       14.8     0.8928       3.6        7.2
25689  112.34  110.54      10.6       21.0     0.9600       3.2        6.0

       3p%_max_5  ft_max_5  fta_max_5  orb_max_5  drb_max_5  trb_max_5  \
25688     0.8134       6.4        7.8        4.0        6.8        9.2
25689     0.8834      10.0       11.2        3.4        7.2       10.0

       ast_max_5  stl_max_5  blk_max_5  tov_max_5  pf_max_5  pts_max_5  \
25688        7.2        4.0        2.4        4.6       5.0       22.4
25689        5.8        3.2        2.0        4.6       3.8       31.2

       gmsc_max_5  ts%_max_5  efg%_max_5  3par_max_5  ftr_max_5  orb%_max_5  \
25688       20.16     1.0288      1.0524      0.8276     1.8134       20.80
25689       22.90     1.2352      1.2700      1.0000     1.1222       22.36

       drb%_max_5  trb%_max_5  ast%_max_5  stl%_max_5  blk%_max_5  tov%_max_5  \
25688       35.84       19.98       53.26        8.14        8.24       63.42
25689       37.08       23.58       38.86        6.92       13.10       34.98

       usg%_max_5  ortg_max_5  drtg_max_5  total_5  home_5  won_5  \
25688       29.52       178.4       123.2    108.8     0.6    0.4
25689       36.10       218.8       118.4    110.4     0.4    0.6

       days_rested_5  mp_10  fg_10  fga_10  fg%_10  3p_10  3pa_10  3p%_10  \
25688            2.8  240.0   38.8    82.8  0.4675   11.8    32.5  0.3600
25689            2.8  240.0   40.6    86.2  0.4700   11.4    32.4  0.3468

       ft_10  fta_10  orb_10  drb_10  trb_10  ast_10  stl_10  blk_10  tov_10  \
25688   21.3    27.0     8.2    29.7    37.9    24.4    10.4     5.6    14.7
25689   22.2    26.8    11.0    30.3    41.3    21.5    10.5     4.9    14.4

       pf_10  pts_10  ts%_10  efg%_10  3par_10  ftr_10  orb%_10  drb%_10  \
25688   24.0   110.7  0.5844   0.5384   0.3922  0.3289    20.57    73.08
25689   21.3   114.8  0.5852   0.5353   0.3739  0.3158    26.34    72.05

       trb%_10  ast%_10  stl%_10  blk%_10  tov%_10  usg%_10  ortg_10  drtg_10  \
25688    47.32    63.06    10.56    10.53    13.40    100.0   112.94   113.04
25689    49.82    52.35    10.69    10.10    12.88    100.0   116.72   112.05

       fg_max_10  fga_max_10  fg%_max_10  3p_max_10  3pa_max_10  3p%_max_10  \
25688        8.7        16.6      0.8798        3.3         7.6      0.8567
25689       11.0        21.3      0.9400        3.3         7.0      0.8584

       ft_max_10  fta_max_10  orb_max_10  drb_max_10  trb_max_10  ast_max_10  \
25688        7.1         8.6         3.1         7.3         8.8         8.8
25689        9.4        10.6         3.0         7.2         9.4         6.8

       stl_max_10  blk_max_10  tov_max_10  pf_max_10  pts_max_10  gmsc_max_10  \
25688         3.8         2.5         4.0        4.9        25.7        22.85
25689         3.0         1.9         4.1        4.2        31.7        25.06

       ts%_max_10  efg%_max_10  3par_max_10  ftr_max_10  orb%_max_10  \
25688      1.0508       1.0762       0.8805      1.6767        21.51
25689      1.2069       1.2375       1.0000      1.0859        21.92

       drb%_max_10  trb%_max_10  ast%_max_10  stl%_max_10  blk%_max_10  \
25688        37.96        21.13        54.17         6.81         8.24
25689        39.12        25.25        40.69         7.45        13.10

       tov%_max_10  usg%_max_10  ortg_max_10  drtg_max_10  total_10  home_10  \
25688        60.75         32.8        175.2        123.2     110.7      0.6
25689        47.49         34.6        223.4        120.6     114.8      0.5

       won_10  days_rested_10  mp_opp_10  fg_opp_10  fga_opp_10  fg%_opp_10  \
25688     0.5             2.4      240.0       40.6        86.2      0.4700
25689     0.7             2.5      240.0       38.8        82.8      0.4675

       3p_opp_10  3pa_opp_10  3p%_opp_10  ft_opp_10  fta_opp_10  orb_opp_10  \
25688       11.4        32.4      0.3468       22.2        26.8        11.0
25689       11.8        32.5      0.3600       21.3        27.0         8.2

       drb_opp_10  trb_opp_10  ast_opp_10  stl_opp_10  blk_opp_10  tov_opp_10  \
25688        30.3        41.3        21.5        10.5         4.9        14.4
25689        29.7        37.9        24.4        10.4         5.6        14.7

       pf_opp_10  pts_opp_10  ts%_opp_10  efg%_opp_10  3par_opp_10  \
25688       21.3       114.8      0.5852       0.5353       0.3739
25689       24.0       110.7      0.5844       0.5384       0.3922

       ftr_opp_10  orb%_opp_10  drb%_opp_10  trb%_opp_10  ast%_opp_10  \
25688      0.3158        26.34        72.05        49.82        52.35
25689      0.3289        20.57        73.08        47.32        63.06

       stl%_opp_10  blk%_opp_10  tov%_opp_10  usg%_opp_10  ortg_opp_10  \
25688        10.69        10.10        12.88        100.0       116.72
25689        10.56        10.53        13.40        100.0       112.94

       drtg_opp_10  fg_max_opp_10  fga_max_opp_10  fg%_max_opp_10  \
25688       112.05           11.0            21.3          0.9400
25689       113.04            8.7            16.6          0.8798

       3p_max_opp_10  3pa_max_opp_10  3p%_max_opp_10  ft_max_opp_10  \
25688            3.3             7.0          0.8584            9.4
25689            3.3             7.6          0.8567            7.1

       fta_max_opp_10  orb_max_opp_10  drb_max_opp_10  trb_max_opp_10  \
25688            10.6             3.0             7.2             9.4
25689             8.6             3.1             7.3             8.8

       ast_max_opp_10  stl_max_opp_10  blk_max_opp_10  tov_max_opp_10  \
25688             6.8             3.0             1.9             4.1
25689             8.8             3.8             2.5             4.0

       pf_max_opp_10  pts_max_opp_10  gmsc_max_opp_10  ts%_max_opp_10  \
25688            4.2            31.7            25.06          1.2069
25689            4.9            25.7            22.85          1.0508

       efg%_max_opp_10  3par_max_opp_10  ftr_max_opp_10  orb%_max_opp_10  \
25688           1.2375           1.0000          1.0859            21.92
25689           1.0762           0.8805          1.6767            21.51

       drb%_max_opp_10  trb%_max_opp_10  ast%_max_opp_10  stl%_max_opp_10  \
25688            39.12            25.25            40.69             7.45
25689            37.96            21.13            54.17             6.81

       blk%_max_opp_10  tov%_max_opp_10  usg%_max_opp_10  ortg_max_opp_10  \
25688            13.10            47.49             34.6            223.4
25689             8.24            60.75             32.8            175.2

       drtg_max_opp_10  total_opp_10  home_opp_10  won_opp_10  \
25688            120.6         114.8          0.5         0.7
25689            123.2         110.7          0.6         0.5

       days_rested_opp_10  mp_opp_5  fg_opp_5  fga_opp_5  fg%_opp_5  3p_opp_5  \
25688                 2.5     240.0      37.0       81.4     0.4550       9.8
25689                 2.4     240.0      38.0       84.2     0.4516      12.0

       3pa_opp_5  3p%_opp_5  ft_opp_5  fta_opp_5  orb_opp_5  drb_opp_5  \
25688       27.2     0.3474      26.6       31.8       11.0       31.8
25689       35.0     0.3426      20.8       27.2       10.0       30.0

       trb_opp_5  ast_opp_5  stl_opp_5  blk_opp_5  tov_opp_5  pf_opp_5  \
25688       42.8       18.0        9.4        5.4       16.2      22.0
25689       40.0       23.6       11.6        5.8       15.8      23.6

       pts_opp_5  ts%_opp_5  efg%_opp_5  3par_opp_5  ftr_opp_5  orb%_opp_5  \
25688      110.4     0.5782      0.5144      0.3334     0.3920       26.22
25689      108.8     0.5664      0.5230      0.4158     0.3254       23.52

       drb%_opp_5  trb%_opp_5  ast%_opp_5  stl%_opp_5  blk%_opp_5  tov%_opp_5  \
25688       76.48        52.0       48.12        9.60       10.86       14.64
25689       73.78        48.0       62.40       11.76       11.00       14.06

       usg%_opp_5  ortg_opp_5  drtg_opp_5  fg_max_opp_5  fga_max_opp_5  \
25688       100.0      112.34      110.54          10.6           21.0
25689       100.0      110.54      112.34           7.6           14.8

       fg%_max_opp_5  3p_max_opp_5  3pa_max_opp_5  3p%_max_opp_5  \
25688         0.9600           3.2            6.0         0.8834
25689         0.8928           3.6            7.2         0.8134

       ft_max_opp_5  fta_max_opp_5  orb_max_opp_5  drb_max_opp_5  \
25688          10.0           11.2            3.4            7.2
25689           6.4            7.8            4.0            6.8

       trb_max_opp_5  ast_max_opp_5  stl_max_opp_5  blk_max_opp_5  \
25688           10.0            5.8            3.2            2.0
25689            9.2            7.2            4.0            2.4

       tov_max_opp_5  pf_max_opp_5  pts_max_opp_5  gmsc_max_opp_5  \
25688            4.6           3.8           31.2           22.90
25689            4.6           5.0           22.4           20.16

       ts%_max_opp_5  efg%_max_opp_5  3par_max_opp_5  ftr_max_opp_5  \
25688         1.2352          1.2700          1.0000         1.1222
25689         1.0288          1.0524          0.8276         1.8134

       orb%_max_opp_5  drb%_max_opp_5  trb%_max_opp_5  ast%_max_opp_5  \
25688           22.36           37.08           23.58           38.86
25689           20.80           35.84           19.98           53.26

       stl%_max_opp_5  blk%_max_opp_5  tov%_max_opp_5  usg%_max_opp_5  \
25688            6.92           13.10           34.98           36.10
25689            8.14            8.24           63.42           29.52

       ortg_max_opp_5  drtg_max_opp_5  total_opp_5  home_opp_5  won_opp_5  \
25688           218.8           118.4        110.4         0.4        0.6
25689           178.4           123.2        108.8         0.6        0.4

       days_rested_opp_5
25688                2.8
25689                2.8

In [89]:
df = df.dropna() #Drop all null/na values

In [90]:
df.describe()

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,stl%_max_opp_5,blk%_max_opp_5,tov%_max_opp_5,usg%_max_opp_5,ortg_max_opp_5,drtg_max_opp_5,total_opp_5,home_opp_5,won_opp_5,days_rested_opp_5
count,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,...,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000,12310.000000
mean,241.397238,41.393501,88.350853,0.469438,12.721690,35.260195,0.359983,17.262551,22.121608,10.445816,...,6.039667,9.606656,40.088865,35.205241,184.830038,122.509311,112.848455,0.500356,0.503726,2.027326
std,6.347683,5.283804,7.066354,0.055160,3.917362,6.922652,0.083728,5.807592,6.961280,3.839976,...,2.208971,3.610381,10.216076,4.477366,20.212696,5.768240,7.023818,0.227426,0.254906,0.261905
min,240.000000,22.000000,64.000000,0.277000,2.000000,10.000000,0.069000,0.000000,0.000000,0.000000,...,1.700000,2.180000,16.520000,25.620000,131.750000,101.600000,88.600000,0.000000,0.000000,1.400000
25%,240.000000,38.000000,84.000000,0.432000,10.000000,30.000000,0.303000,13.000000,17.000000,8.000000,...,4.700000,7.240000,32.320000,32.180000,170.400000,118.600000,108.000000,0.400000,0.400000,1.800000
50%,240.000000,41.000000,88.000000,0.469000,12.000000,35.000000,0.357000,17.000000,22.000000,10.000000,...,5.580000,8.900000,38.680000,34.400000,183.500000,122.500000,112.800000,0.500000,0.500000,2.000000
75%,240.000000,45.000000,93.000000,0.506000,15.000000,40.000000,0.415000,21.000000,27.000000,13.000000,...,6.740000,11.120000,46.460000,37.225000,197.800000,126.400000,117.800000,0.600000,0.600000,2.200000
max,315.000000,65.000000,121.000000,0.689000,29.000000,63.000000,0.684000,44.000000,53.000000,29.000000,...,30.375000,36.925000,100.000000,66.250000,278.600000,144.800000,136.800000,1.000000,1.000000,3.200000

In [91]:
for col in df.columns:
    print(col)

mp
fg
fga
fg%
3p
3pa
3p%
ft
fta
orb
drb
trb
ast
stl
blk
tov
pf
pts
ts%
efg%
3par
ftr
orb%
drb%
trb%
ast%
stl%
blk%
tov%
usg%
ortg
drtg
fg_max
fga_max
fg%_max
3p_max
3pa_max
3p%_max
ft_max
fta_max
orb_max
drb_max
trb_max
ast_max
stl_max
blk_max
tov_max
pf_max
pts_max
gmsc_max
ts%_max
efg%_max
3par_max
ftr_max
orb%_max
drb%_max
trb%_max
ast%_max
stl%_max
blk%_max
tov%_max
usg%_max
ortg_max
drtg_max
team
total
home
mp_opp
fg_opp
fga_opp
fg%_opp
3p_opp
3pa_opp
3p%_opp
ft_opp
fta_opp
orb_opp
drb_opp
trb_opp
ast_opp
stl_opp
blk_opp
tov_opp
pf_opp
pts_opp
ts%_opp
efg%_opp
3par_opp
ftr_opp
orb%_opp
drb%_opp
trb%_opp
ast%_opp
stl%_opp
blk%_opp
tov%_opp
usg%_opp
ortg_opp
drtg_opp
fg_max_opp
fga_max_opp
fg%_max_opp
3p_max_opp
3pa_max_opp
3p%_max_opp
ft_max_opp
fta_max_opp
orb_max_opp
drb_max_opp
trb_max_opp
ast_max_opp
stl_max_opp
blk_max_opp
tov_max_opp
pf_max_opp
pts_max_opp
gmsc_max_opp
ts%_max_opp
efg%_max_opp
3par_max_opp
ftr_max_opp
orb%_max_opp
drb%_max_opp
trb%_max_opp
ast%_max_opp
stl%_max_opp
blk%_max_opp
tov%_max_opp
usg%_max_opp
ortg_max_opp
drtg_max_opp
team_opp
total_opp
home_opp
season
date
won
won_opp
prev_date
days_rested
prev_date_opp
days_rested_opp
mp_5
fg_5
fga_5
fg%_5
3p_5
3pa_5
3p%_5
ft_5
fta_5
orb_5
drb_5
trb_5
ast_5
stl_5
blk_5
tov_5
pf_5
pts_5
ts%_5
efg%_5
3par_5
ftr_5
orb%_5
drb%_5
trb%_5
ast%_5
stl%_5
blk%_5
tov%_5
usg%_5
ortg_5
drtg_5
fg_max_5
fga_max_5
fg%_max_5
3p_max_5
3pa_max_5
3p%_max_5
ft_max_5
fta_max_5
orb_max_5
drb_max_5
trb_max_5
ast_max_5
stl_max_5
blk_max_5
tov_max_5
pf_max_5
pts_max_5
gmsc_max_5
ts%_max_5
efg%_max_5
3par_max_5
ftr_max_5
orb%_max_5
drb%_max_5
trb%_max_5
ast%_max_5
stl%_max_5
blk%_max_5
tov%_max_5
usg%_max_5
ortg_max_5
drtg_max_5
total_5
home_5
won_5
days_rested_5
mp_10
fg_10
fga_10
fg%_10
3p_10
3pa_10
3p%_10
ft_10
fta_10
orb_10
drb_10
trb_10
ast_10
stl_10
blk_10
tov_10
pf_10
pts_10
ts%_10
efg%_10
3par_10
ftr_10
orb%_10
drb%_10
trb%_10
ast%_10
stl%_10
blk%_10
tov%_10
usg%_10
ortg_10
drtg_10
fg_max_10
fga_max_10
fg%_max_10
3p_max_10
3pa_max_10
3p%_max_10
ft_max_10
fta_max_10
orb_max_10
drb_max_10
trb_max_10
ast_max_10
stl_max_10
blk_max_10
tov_max_10
pf_max_10
pts_max_10
gmsc_max_10
ts%_max_10
efg%_max_10
3par_max_10
ftr_max_10
orb%_max_10
drb%_max_10
trb%_max_10
ast%_max_10
stl%_max_10
blk%_max_10
tov%_max_10
usg%_max_10
ortg_max_10
drtg_max_10
total_10
home_10
won_10
days_rested_10
mp_opp_10
fg_opp_10
fga_opp_10
fg%_opp_10
3p_opp_10
3pa_opp_10
3p%_opp_10
ft_opp_10
fta_opp_10
orb_opp_10
drb_opp_10
trb_opp_10
ast_opp_10
stl_opp_10
blk_opp_10
tov_opp_10
pf_opp_10
pts_opp_10
ts%_opp_10
efg%_opp_10
3par_opp_10
ftr_opp_10
orb%_opp_10
drb%_opp_10
trb%_opp_10
ast%_opp_10
stl%_opp_10
blk%_opp_10
tov%_opp_10
usg%_opp_10
ortg_opp_10
drtg_opp_10
fg_max_opp_10
fga_max_opp_10
fg%_max_opp_10
3p_max_opp_10
3pa_max_opp_10
3p%_max_opp_10
ft_max_opp_10
fta_max_opp_10
orb_max_opp_10
drb_max_opp_10
trb_max_opp_10
ast_max_opp_10
stl_max_opp_10
blk_max_opp_10
tov_max_opp_10
pf_max_opp_10
pts_max_opp_10
gmsc_max_opp_10
ts%_max_opp_10
efg%_max_opp_10
3par_max_opp_10
ftr_max_opp_10
orb%_max_opp_10
drb%_max_opp_10
trb%_max_opp_10
ast%_max_opp_10
stl%_max_opp_10
blk%_max_opp_10
tov%_max_opp_10
usg%_max_opp_10
ortg_max_opp_10
drtg_max_opp_10
total_opp_10
home_opp_10
won_opp_10
days_rested_opp_10
mp_opp_5
fg_opp_5
fga_opp_5
fg%_opp_5
3p_opp_5
3pa_opp_5
3p%_opp_5
ft_opp_5
fta_opp_5
orb_opp_5
drb_opp_5
trb_opp_5
ast_opp_5
stl_opp_5
blk_opp_5
tov_opp_5
pf_opp_5
pts_opp_5
ts%_opp_5
efg%_opp_5
3par_opp_5
ftr_opp_5
orb%_opp_5
drb%_opp_5
trb%_opp_5
ast%_opp_5
stl%_opp_5
blk%_opp_5
tov%_opp_5
usg%_opp_5
ortg_opp_5
drtg_opp_5
fg_max_opp_5
fga_max_opp_5
fg%_max_opp_5
3p_max_opp_5
3pa_max_opp_5
3p%_max_opp_5
ft_max_opp_5
fta_max_opp_5
orb_max_opp_5
drb_max_opp_5
trb_max_opp_5
ast_max_opp_5
stl_max_opp_5
blk_max_opp_5
tov_max_opp_5
pf_max_opp_5
pts_max_opp_5
gmsc_max_opp_5
ts%_max_opp_5
efg%_max_opp_5
3par_max_opp_5
ftr_max_opp_5
orb%_max_opp_5
drb%_max_opp_5
trb%_max_opp_5
ast%_max_opp_5
stl%_max_opp_5
blk%_max_opp_5
tov%_max_opp_5
usg%_max_opp_5
ortg_max_opp_5
drtg_max_opp_5
total_opp_5
home_opp_5
won_opp_5
days_rested_opp_5

In [92]:
df[["team","team_opp","won_10","won_opp_10","date"]]

      team team_opp    won_10  won_opp_10       date
12810  MIL      GSW  0.444444    0.333333 2020-12-25
12811  GSW      MIL  0.333333    0.444444 2020-12-25
12812  MIA      NOP  0.444444    0.777778 2020-12-25
12813  NOP      MIA  0.777778    0.444444 2020-12-25
12814  LAL      DAL  0.777778    0.555556 2020-12-25
...    ...      ...       ...         ...        ...
25685  OKC      IND  0.700000    0.600000 2025-06-16
25686  OKC      IND  0.700000    0.500000 2025-06-19
25687  IND      OKC  0.500000    0.700000 2025-06-19
25688  IND      OKC  0.500000    0.700000 2025-06-22
25689  OKC      IND  0.700000    0.500000 2025-06-22

[12310 rows x 5 columns]

## Difference Features
To reduce the complexity of the features and the potential for noise to reduce model performance, we can change the features to be the difference in stats between the two teams playing instead of inputting each team's performance.

For example, instead of having **"fg%_10"** and **"fg%_opp_10"**, we can just have **"fg%_diff"** where **fg%_diff = fg%_10 - fg%_opp_10**

In [93]:
def get_team_diff(df):
    #Select all rolling columns and remove invalid columns
    selected_columns = [c for c in df.columns if "_10" in c or "_5" in c]
    
    #If a col has _opp, then it also has the same col for the other team
    selected_columns = [c for c in selected_columns if "_opp" in c]
    
    #Create new df
    df_diff_only = pd.DataFrame(index=df.index)
    
    #For each column, if there is another column with the exact string, without the _opp
    for col in selected_columns:
        other_col = col.replace("_opp", "")
        
        #Compute difference for each numeric column and Add to empty df
        if other_col in df.columns:
            df_diff_only[f"{other_col}_diff"] = df[other_col] - df[col]
            
    return df_diff_only

df_diff = get_team_diff(df)

C:\Users\henXc\AppData\Local\Temp/ipykernel_37016/3822363202.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df_diff_only[f"{other_col}_diff"] = df[other_col] - df[col]

In [94]:
df_diff.head()

,mp_10_diff,fg_10_diff,fga_10_diff,fg%_10_diff,3p_10_diff,3pa_10_diff,3p%_10_diff,ft_10_diff,fta_10_diff,orb_10_diff,...,stl%_max_5_diff,blk%_max_5_diff,tov%_max_5_diff,usg%_max_5_diff,ortg_max_5_diff,drtg_max_5_diff,total_5_diff,home_5_diff,won_5_diff,days_rested_5_diff
12810,2.777778,3.888889,2.777778,0.027111,2.777778,2.777778,0.056111,-5.777778,-7.444444,-0.777778,...,-3.650,2.075,15.275,-2.025,1.25,10.00,4.0,-0.25,0.00,0.25
12811,-2.777778,-3.888889,-2.777778,-0.027111,-2.777778,-2.777778,-0.056111,5.777778,7.444444,0.777778,...,3.650,-2.075,-15.275,2.025,-1.25,-10.00,-4.0,0.25,0.00,-0.25
12812,0.000000,0.888889,6.555556,-0.026222,-0.555556,-0.333333,-0.013000,-1.888889,-3.444444,0.000000,...,-1.600,20.475,24.500,1.900,-27.25,0.00,-12.5,-0.25,-0.25,0.25
12813,0.000000,-0.888889,-6.555556,0.026222,0.555556,0.333333,0.013000,1.888889,3.444444,0.000000,...,1.600,-20.475,-24.500,-1.900,27.25,0.00,12.5,0.25,0.25,-0.25
12814,-2.777778,2.444444,-3.666667,0.043889,-2.888889,-10.222222,0.024333,-7.222222,-8.333333,-1.777778,...,-0.325,0.750,11.975,-2.150,-1.50,7.25,-12.5,0.50,0.00,0.25

In [95]:
for col in df_diff.columns:
    print(col)

mp_10_diff
fg_10_diff
fga_10_diff
fg%_10_diff
3p_10_diff
3pa_10_diff
3p%_10_diff
ft_10_diff
fta_10_diff
orb_10_diff
drb_10_diff
trb_10_diff
ast_10_diff
stl_10_diff
blk_10_diff
tov_10_diff
pf_10_diff
pts_10_diff
ts%_10_diff
efg%_10_diff
3par_10_diff
ftr_10_diff
orb%_10_diff
drb%_10_diff
trb%_10_diff
ast%_10_diff
stl%_10_diff
blk%_10_diff
tov%_10_diff
usg%_10_diff
ortg_10_diff
drtg_10_diff
fg_max_10_diff
fga_max_10_diff
fg%_max_10_diff
3p_max_10_diff
3pa_max_10_diff
3p%_max_10_diff
ft_max_10_diff
fta_max_10_diff
orb_max_10_diff
drb_max_10_diff
trb_max_10_diff
ast_max_10_diff
stl_max_10_diff
blk_max_10_diff
tov_max_10_diff
pf_max_10_diff
pts_max_10_diff
gmsc_max_10_diff
ts%_max_10_diff
efg%_max_10_diff
3par_max_10_diff
ftr_max_10_diff
orb%_max_10_diff
drb%_max_10_diff
trb%_max_10_diff
ast%_max_10_diff
stl%_max_10_diff
blk%_max_10_diff
tov%_max_10_diff
usg%_max_10_diff
ortg_max_10_diff
drtg_max_10_diff
total_10_diff
home_10_diff
won_10_diff
days_rested_10_diff
mp_5_diff
fg_5_diff
fga_5_diff
fg%_5_diff
3p_5_diff
3pa_5_diff
3p%_5_diff
ft_5_diff
fta_5_diff
orb_5_diff
drb_5_diff
trb_5_diff
ast_5_diff
stl_5_diff
blk_5_diff
tov_5_diff
pf_5_diff
pts_5_diff
ts%_5_diff
efg%_5_diff
3par_5_diff
ftr_5_diff
orb%_5_diff
drb%_5_diff
trb%_5_diff
ast%_5_diff
stl%_5_diff
blk%_5_diff
tov%_5_diff
usg%_5_diff
ortg_5_diff
drtg_5_diff
fg_max_5_diff
fga_max_5_diff
fg%_max_5_diff
3p_max_5_diff
3pa_max_5_diff
3p%_max_5_diff
ft_max_5_diff
fta_max_5_diff
orb_max_5_diff
drb_max_5_diff
trb_max_5_diff
ast_max_5_diff
stl_max_5_diff
blk_max_5_diff
tov_max_5_diff
pf_max_5_diff
pts_max_5_diff
gmsc_max_5_diff
ts%_max_5_diff
efg%_max_5_diff
3par_max_5_diff
ftr_max_5_diff
orb%_max_5_diff
drb%_max_5_diff
trb%_max_5_diff
ast%_max_5_diff
stl%_max_5_diff
blk%_max_5_diff
tov%_max_5_diff
usg%_max_5_diff
ortg_max_5_diff
drtg_max_5_diff
total_5_diff
home_5_diff
won_5_diff
days_rested_5_diff

In [96]:
selected_columns = ["season","date","home","team","home_opp","team_opp","won"]
df = pd.concat([df[selected_columns], df_diff], axis=1)

In [97]:
df.head()

,season,date,home,team,home_opp,team_opp,won,mp_10_diff,fg_10_diff,fga_10_diff,...,stl%_max_5_diff,blk%_max_5_diff,tov%_max_5_diff,usg%_max_5_diff,ortg_max_5_diff,drtg_max_5_diff,total_5_diff,home_5_diff,won_5_diff,days_rested_5_diff
12810,2021,2020-12-25,1,MIL,0,GSW,True,2.777778,3.888889,2.777778,...,-3.650,2.075,15.275,-2.025,1.25,10.00,4.0,-0.25,0.00,0.25
12811,2021,2020-12-25,0,GSW,1,MIL,False,-2.777778,-3.888889,-2.777778,...,3.650,-2.075,-15.275,2.025,-1.25,-10.00,-4.0,0.25,0.00,-0.25
12812,2021,2020-12-25,1,MIA,0,NOP,True,0.000000,0.888889,6.555556,...,-1.600,20.475,24.500,1.900,-27.25,0.00,-12.5,-0.25,-0.25,0.25
12813,2021,2020-12-25,0,NOP,1,MIA,False,0.000000,-0.888889,-6.555556,...,1.600,-20.475,-24.500,-1.900,27.25,0.00,12.5,0.25,0.25,-0.25
12814,2021,2020-12-25,1,LAL,0,DAL,True,-2.777778,2.444444,-3.666667,...,-0.325,0.750,11.975,-2.150,-1.50,7.25,-12.5,0.50,0.00,0.25

### Balancing the dataset

In [98]:
print(len(df[df['won'] == 1]))
print(len(df[df['won'] == 0]))

6155
6155

In [99]:
from sklearn.utils import resample

def balance_dataframe(df):
    wins = df[df['won'] == 1]
    losses = df[df['won'] == 0]
    
    if len(wins) == len(losses): return df
    if len(wins) > len(losses):
        wins_down = resample(wins,
                   replace=False,
                   n_samples=len(losses),
                   random_state=42)

        return pd.concat([losses, wins_down])
    
    losses_down = resample(losses,
               replace=False,
               n_samples=len(wins),
               random_state=42)
    return pd.concat([wins, losses_down])

df = balance_dataframe(df)

In [100]:
print(len(df[df['won'] == 1]))
print(len(df[df['won'] == 0]))

6155
6155

# Final Dataframe
The final features must only include past data and current information, that can both be inputted into the model.

For the ai model to predict which team is going to win, it needs the recent stats from each team playing.

### The primary key used for finding the most recent game played and pull statistics from that game
- season
- date
- team (home team)
- team_opp (away team)

### Information the model uses to make predictions
- rolling 10-game averages team (contains '_10')
- rolling 10-game averages team_opp (contains '_opp_10')
- rolling 5-game averages team (contains '_5')
- rolling 5-game averages team_opp (contains '_opp_5')
- team performance against team_opp in past 3 games
- team_opp performance against team in past 3 games
- days rested team
- days rested team_opp

### Label/Outcome/Loss/Class
- won   <-- used as label, test model performance with this feature

In [101]:
cols_10 = [col for col in df.columns if "_10" in col]
cols_5 = [col for col in df.columns if "_5" in col]
selected_columns = ["season","date","home","team","team_opp"] + cols_5 + cols_10 + ["won"]

In [102]:
for column in selected_columns:
    print(column)

season
date
home
team
team_opp
mp_5_diff
fg_5_diff
fga_5_diff
fg%_5_diff
3p_5_diff
3pa_5_diff
3p%_5_diff
ft_5_diff
fta_5_diff
orb_5_diff
drb_5_diff
trb_5_diff
ast_5_diff
stl_5_diff
blk_5_diff
tov_5_diff
pf_5_diff
pts_5_diff
ts%_5_diff
efg%_5_diff
3par_5_diff
ftr_5_diff
orb%_5_diff
drb%_5_diff
trb%_5_diff
ast%_5_diff
stl%_5_diff
blk%_5_diff
tov%_5_diff
usg%_5_diff
ortg_5_diff
drtg_5_diff
fg_max_5_diff
fga_max_5_diff
fg%_max_5_diff
3p_max_5_diff
3pa_max_5_diff
3p%_max_5_diff
ft_max_5_diff
fta_max_5_diff
orb_max_5_diff
drb_max_5_diff
trb_max_5_diff
ast_max_5_diff
stl_max_5_diff
blk_max_5_diff
tov_max_5_diff
pf_max_5_diff
pts_max_5_diff
gmsc_max_5_diff
ts%_max_5_diff
efg%_max_5_diff
3par_max_5_diff
ftr_max_5_diff
orb%_max_5_diff
drb%_max_5_diff
trb%_max_5_diff
ast%_max_5_diff
stl%_max_5_diff
blk%_max_5_diff
tov%_max_5_diff
usg%_max_5_diff
ortg_max_5_diff
drtg_max_5_diff
total_5_diff
home_5_diff
won_5_diff
days_rested_5_diff
mp_10_diff
fg_10_diff
fga_10_diff
fg%_10_diff
3p_10_diff
3pa_10_diff
3p%_10_diff
ft_10_diff
fta_10_diff
orb_10_diff
drb_10_diff
trb_10_diff
ast_10_diff
stl_10_diff
blk_10_diff
tov_10_diff
pf_10_diff
pts_10_diff
ts%_10_diff
efg%_10_diff
3par_10_diff
ftr_10_diff
orb%_10_diff
drb%_10_diff
trb%_10_diff
ast%_10_diff
stl%_10_diff
blk%_10_diff
tov%_10_diff
usg%_10_diff
ortg_10_diff
drtg_10_diff
fg_max_10_diff
fga_max_10_diff
fg%_max_10_diff
3p_max_10_diff
3pa_max_10_diff
3p%_max_10_diff
ft_max_10_diff
fta_max_10_diff
orb_max_10_diff
drb_max_10_diff
trb_max_10_diff
ast_max_10_diff
stl_max_10_diff
blk_max_10_diff
tov_max_10_diff
pf_max_10_diff
pts_max_10_diff
gmsc_max_10_diff
ts%_max_10_diff
efg%_max_10_diff
3par_max_10_diff
ftr_max_10_diff
orb%_max_10_diff
drb%_max_10_diff
trb%_max_10_diff
ast%_max_10_diff
stl%_max_10_diff
blk%_max_10_diff
tov%_max_10_diff
usg%_max_10_diff
ortg_max_10_diff
drtg_max_10_diff
total_10_diff
home_10_diff
won_10_diff
days_rested_10_diff
won

In [103]:
df = df.sort_values("date")

In [104]:
df[selected_columns].tail()

,season,date,home,team,team_opp,mp_5_diff,fg_5_diff,fga_5_diff,fg%_5_diff,3p_5_diff,...,blk%_max_10_diff,tov%_max_10_diff,usg%_max_10_diff,ortg_max_10_diff,drtg_max_10_diff,total_10_diff,home_10_diff,won_10_diff,days_rested_10_diff,won
25685,2025,2025-06-16,1,OKC,IND,0.0,3.4,3.2,0.0236,-0.8,...,-0.82,-10.51,4.08,46.4,-1.6,2.3,-0.1,0.1,0.1,True
25686,2025,2025-06-19,0,OKC,IND,0.0,0.4,1.4,-0.0014,-1.4,...,2.22,-11.74,4.07,48.5,-2.7,5.1,0.0,0.2,0.1,False
25687,2025,2025-06-19,1,IND,OKC,0.0,-0.4,-1.4,0.0014,1.4,...,-2.22,11.74,-4.07,-48.5,2.7,-5.1,0.0,-0.2,-0.1,True
25688,2025,2025-06-22,0,IND,OKC,0.0,1.0,2.8,-0.0034,2.2,...,-4.86,13.26,-1.80,-48.2,2.6,-4.1,0.1,-0.2,-0.1,False
25689,2025,2025-06-22,1,OKC,IND,0.0,-1.0,-2.8,0.0034,-2.2,...,4.86,-13.26,1.80,48.2,-2.6,4.1,-0.1,0.2,0.1,True

In [105]:
df = df[selected_columns]

In [106]:
df.to_pickle('data/df_nba_games.pkl')